### ISSUE TITLE
Move this code to jenkins.io repository

### ISSUE THREAD

**Issue by hervelemeur** [jenkins-infra/awestruct-ibeams#16]
> I guess this repo won't have any updates anymore -- in case any changes are needed here, the code should be just moved to jenkins.io repo to simlify the workflow.

_Originally posted by @zbynek in https://github.com/jenkins-infra/awestruct-ibeams/issues/15#issuecomment-1464593210_

**Comment by lemeurherve** [comment]
Done by @zbynek in https://github.com/jenkins-infra/jenkins.io/pull/6291, archiving this repository.
