### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/awestruct-ibeams#9]
Hey @MarkEWaite,

would you mind cutting a release of this gem, please? That would allow us to move forward with jenkins.io and consume more up-to-date dependencies.

Thanks in advance!

**Comment by lemeurherve** [comment]
Done by manually adding a tag and creating a release, but not published on rubygems.org: https://github.com/jenkins-infra/awestruct-ibeams/releases/tag/v0.4.4

Corresponding PR to picj it up on jenkins.io: https://github.com/jenkins-infra/jenkins.io/pull/6139
